# Переопределяем префикс
set-option -g prefix C-b
unbind-key C-a
bind-key C-b send-prefix

bind-key C command-prompt -p "Name of new session: " "new-session -s '%%'"

# Устанавливаем цвет статус-бара
set-option -g status-style bg=red
